sudo: required

services:
    - docker

before_install:
    - docker build -t shadrach19/brightminds .

script:
    - docker run -e CI=true shadrach19/brightminds npm run test
  

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: bright-minds
    env: Brightminds-env
    bucket_name: elasticbeanstalk-us-east-1-751808579985
    bucket_path: bright-minds
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    on:
        branch: staging