sudo: required

services:
    - docker

before_install:
    - docker build -t shadrach19/brightminds .

script:
    - npm run db:migrate:prod
    - npm run db:seed:prod
    - docker run -e CI=true shadrach19/brightminds npm run test
  

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: brightminds
    env: Brightminds-env-1
    bucket_name: elasticbeanstalk-us-east-1-995117905859
    bucket_path: brightminds
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    on:
        branch: staging