export enum EmailTypes {
  SIGNUP = 'SIGN_UP',
  USER_CREATED = 'USER_CREATED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_REOPENED = 'TICKET_REOPENED',
  TICKET_CLOSED = 'TICKET_CLOSED',
  TICKET_RESOLVED = 'TICKET_RESOLVED',
}

export enum NotificationTypes {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_REOPENED = 'TICKET_REOPENED',
  TICKET_CLOSED = 'TICKET_CLOSED',
  TICKET_RESOLVED = 'TICKET_RESOLVED',
}
