export enum RESOURCES {
  PLANS = 'plans',
  SUBSCRIPTION = 'SUBSCRIPTION',
  PROFILE = 'PROFILE',
  EVENTS = 'EVENTS',
  COMPETITION = 'COMPETITION',
  REMINDERS = 'REMINDERS',
  MEMBER = 'MEMEBER',
  ADMIN = 'ADMIN',
  SUPER_ADMI = 'SUPER_ADMIN',
}
